name: docker_test_0-000003
label: 000.3 docker test
description: Ansible Ping Test
type: docker

labels:
  collection: experimental

variables:
  - name: ip_address
    description: Host IP Address
    default: 10.0.0.1
    type_hint: list
  - name: username
    description: Host Username
    default: admin
    type_hint: text
  - name: password
    description: Host Password
    default:
    type_hint: password
  - name: cli
    description: cli command
    default: show system info
    type_hint: text

# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: ansible_test
    image: paloaltonetworks/pantools
    cmd: ansible -i '{{ ip_address | join(',') }}' op_cmd_example.yml -e 'ip_address={{ FW_USER }}' -e 'username={{ username }}' -e 'password={{ password }}'