name: docker_ansible_test_001
label: Docker Ansible Example
description: An example docker skillet that executes an Ansible Playbook found in this directory

type: docker

labels:
  collection: Example Skillets

variables:
  - name: ip_address
    description: Host IP Address
    default: 10.0.0.1
    type_hint: ip_address
  - name: username
    description: Host Username
    default: admin
    type_hint: text
  - name: password
    description: Host Password
    default:
    type_hint: password
  - name: cli
    description: cli command
    default: show system info
    type_hint: text

snippets:
  - name: ansible_test
    image: registry.gitlab.com/panw-gse/as/panos_skillet_tools:latest
    cmd: |
      ansible-playbook -i 'panorama-1,  ' op_cmd_example.yml
